/* produtos.js — Catálogo completo · Sítio Rosa do Vale */

const PRODUTOS = [

  /* ═══════════════════════════════════════════
     ESPUMANTES NATURAIS — 750ml · R$ 98
  ═══════════════════════════════════════════ */
  {
    id: 'espumante-natural-rose-brut',
    name: 'Espumante Natural Rosé Brut',
    nameFull: 'Espumante Natural Rosé Brut',
    category: 'espumantes',
    subcategory: 'Espumante Natural',
    price: 98,
    img: 'Imagens/Espumante Natural Rosé Brut.png',
    bottleClass: 'bottle-rose',
    volume: '750ml',
    uvas: 'Chardonnay, Riesling Itálico e Merlot',
    alcool: '11,5%',
    servico: '4° a 6°C',
    cor: 'Rosé salmão, brilhante',
    aroma: 'Framboesa, morango e amora',
    boca: 'Fresco e frutado, bolha fina persistente',
    harmoniza: 'Risotos, queijos e canapés',
    descricao: 'Elaborado a partir de uvas Chardonnay, Riesling Itálico e Merlot, em autoclaves, apresenta coloração salmão. Possui aromas de frutas vermelhas como framboesa, morango e amora. Em boca é fresco e frutado. Acompanhamento: risotos, queijos e canapés. Temperatura de serviço: 4° e 6°C · 750ml · 11,5%',
    tag: 'Novidade',
    tagStyle: '',
    featured: true,
    safra: '2024',
    docura: 20, acidez: 75, corpo: 55, bolha: 80, final: 70,
    harmonizacaoChips: ['🦐 Frutos do mar', '🧀 Queijos brancos', '🥗 Saladas com frutas', '🍓 Morango e framboesa', '🍤 Aperitivos'],
  },
  {
    id: 'espumante-natural-branco-brut',
    name: 'Espumante Natural Branco Brut',
    nameFull: 'Espumante Natural Branco Brut',
    category: 'espumantes',
    subcategory: 'Espumante Natural',
    price: 98,
    img: 'Imagens/Espumante Natural Branco Brut.png',
    bottleClass: 'bottle-branco',
    volume: '750ml',
    uvas: 'Chardonnay e Riesling Itálico',
    alcool: '11,5%',
    servico: '4° a 6°C',
    cor: 'Amarelo-palha, brilhante',
    aroma: 'Frutado com notas cítricas',
    boca: 'Frescor e leveza, bolha fina',
    harmoniza: 'Queijos, canapés, pizzas e massas',
    descricao: 'Elaborado a partir de uvas Chardonnay e Riesling Itálico, em autoclaves, apresenta coloração amarelo-palha e aromas frutados com notas cítricas. Em boca apresenta frescor e leveza. Acompanhamento: queijos, canapés, pizzas e massas. Temperatura de serviço: 4° e 6°C · 750ml · 11,5%',
    tag: null,
    tagStyle: '',
    featured: false,
    safra: '2024',
    docura: 18, acidez: 72, corpo: 50, bolha: 80, final: 65,
    harmonizacaoChips: ['🧀 Queijos', '🍕 Pizzas', '🍝 Massas', '🥗 Canapés', '🍤 Aperitivos'],
  },
  {
    id: 'espumante-branco-demi-sec',
    name: 'Espumante Branco Demi Sec',
    nameFull: 'Espumante Branco Demi Sec',
    category: 'espumantes',
    subcategory: 'Espumante Natural',
    price: 98,
    img: 'Imagens/Espumante Branco Demi Sec.png',
    bottleClass: 'bottle-branco',
    volume: '750ml',
    uvas: 'Chardonnay e Riesling Itálico',
    alcool: '11%',
    servico: '4° a 5°C',
    cor: 'Amarelo-palha',
    aroma: 'Frutado e cítrico',
    boca: 'Frescor e leveza, perlage intensa e delicada',
    harmoniza: 'Pizzas, queijos, canapés e massa',
    descricao: 'Elaborado a partir de uvas Chardonnay e Riesling Itálico, apresenta coloração amarelo palha, com perlage intensa e delicada. Possui aroma frutado e cítrico e em boca apresenta frescor e leveza. Acompanhamento: pizzas, queijos, canapés e massa. Temperatura de serviço: entre 4° e 5°C · 750ml · 11%',
    tag: null,
    tagStyle: '',
    featured: false,
    safra: '2024',
    docura: 50, acidez: 60, corpo: 50, bolha: 75, final: 60,
    harmonizacaoChips: ['🍰 Sobremesas', '🍓 Frutas', '🎂 Bolos', '🍕 Pizzas', '🧀 Queijos'],
  },
  {
    id: 'espumante-moscatel-rose',
    name: 'Espumante Moscatel Rosé',
    nameFull: 'Espumante Moscatel Rosé',
    category: 'espumantes',
    subcategory: 'Espumante Moscatel',
    price: 91,
    img: 'Imagens/Espumante Moscatel Rosé.png',
    bottleClass: 'bottle-rose',
    volume: '750ml',
    uvas: 'Moscato',
    alcool: '9%',
    servico: '4° a 6°C',
    cor: 'Rosé, límpido e brilhante',
    aroma: 'Floral intenso e frutas brancas',
    boca: 'Suave, moscatel, bolha fina',
    harmoniza: 'Sobremesas, frutas e aperitivos leves',
    descricao: 'Espumante moscatel rosé com perfil suave e aromático. Notas florais e de frutas brancas características do Moscato. Levemente adocicado, ideal para brindar em qualquer ocasião.',
    tag: null,
    tagStyle: '',
    featured: false,
    safra: '2024',
    docura: 65, acidez: 45, corpo: 40, bolha: 75, final: 55,
    harmonizacaoChips: ['🍓 Frutas vermelhas', '🍰 Sobremesas', '🌸 Aperitivos leves', '🍫 Chocolates'],
  },

  /* ═══════════════════════════════════════════
     ESPUMANTES MÉTODO TRADICIONAL — 750ml
  ═══════════════════════════════════════════ */
  {
    id: 'espumante-brut-rose-tradicional',
    name: 'Espumante Brut Rosé',
    nameFull: 'Espumante Brut Rosé – Método Tradicional',
    category: 'espumantes',
    subcategory: 'Método Tradicional',
    price: 183,
    img: 'Imagens/Espumante Brut Rosé - Método tradicional.png',
    bottleClass: 'bottle-rose',
    volume: '750ml',
    uvas: 'Blend',
    alcool: '11,5%',
    servico: '4° a 6°C',
    cor: 'Rosé salmão brilhante',
    aroma: 'Frutas vermelhas, brioche e delicadas notas tostadas',
    boca: 'Cremoso, persistente, acidez equilibrada',
    harmoniza: 'Risotos, frutos do mar, queijos e pratos delicados',
    descricao: 'Espumante brut rosé elaborado pelo método Champenoise (método tradicional), com perlage fina e persistente. Coloração rosé salmão. No aroma, frutas vermelhas com delicadas notas tostadas. Em boca, cremoso e persistente, com acidez bem equilibrada.',
    tag: 'Método Tradicional',
    tagStyle: 'background:var(--wine); color:var(--cream);',
    featured: true,
    safra: '2024',
    docura: 18, acidez: 78, corpo: 65, bolha: 88, final: 80,
    harmonizacaoChips: ['🦐 Frutos do mar', '🧀 Queijos', '🫕 Risotos', '🐟 Peixes', '🍤 Aperitivos'],
  },
  {
    id: 'espumante-nature-branco-tradicional',
    name: 'Espumante Nature Branco',
    nameFull: 'Espumante Nature Branco – Método Tradicional',
    category: 'espumantes',
    subcategory: 'Método Tradicional',
    price: 210,
    img: 'Imagens/Espumante Nature Branco - Método tradicional.png',
    bottleClass: 'bottle-branco',
    volume: '750ml',
    uvas: 'Chardonnay e Riesling Itálico',
    alcool: '11,5%',
    servico: '4° a 6°C',
    cor: 'Amarelo-dourado brilhante',
    aroma: 'Pão, frutas secas, figo e notas de maturação',
    boca: 'Cremoso, persistente, textura macia e aveludada',
    harmoniza: 'Frutos do mar, peixes nobres, queijos curados',
    descricao: 'Elaborado com uvas Chardonnay e Riesling Itálico pelo método Champenoise, com 24 meses de autólise. Coloração amarelo-dourado brilhante, perlage intensa e duradoura. No aroma, notas de pão, frutas secas e figo. Em boca, cremoso, persistente, com acidez equilibrada e textura macia e aveludada.',
    tag: 'Método Tradicional',
    tagStyle: 'background:var(--wine); color:var(--cream);',
    featured: false,
    safra: '2024',
    docura: 5, acidez: 80, corpo: 70, bolha: 90, final: 85,
    harmonizacaoChips: ['🦐 Frutos do mar', '🐟 Peixes nobres', '🧀 Queijos curados', '🫒 Charcutaria'],
  },
  {
    id: 'espumante-natural-rose-nature-tradicional',
    name: 'Espumante Rosé Nature',
    nameFull: 'Espumante Natural Rosé Nature – Método Tradicional',
    category: 'espumantes',
    subcategory: 'Método Tradicional',
    price: 210,
    img: 'Imagens/Espumante Natural Rosé Nature – Método tradicional.png',
    bottleClass: 'bottle-rose',
    volume: '750ml',
    uvas: 'Chardonnay, Riesling Itálico e Merlot',
    alcool: '11,5%',
    servico: '4° a 6°C',
    cor: 'Rosé salmão',
    aroma: 'Frutas vermelhas, damasco e notas de maturação',
    boca: 'Cremoso, persistente, equilibrado e aveludado',
    harmoniza: 'Frutos do mar, peixes, queijos e pratos delicados',
    descricao: 'Elaborado com uvas Chardonnay, Riesling Itálico e Merlot pelo método Champenoise, com autólise de 24 meses. Espumante rosé salmão com perlage intensa. Aromas de frutas vermelhas, damasco e notas de maturação. Na boca, cremoso, persistente, equilibrado e aveludado. Temperatura de serviço: 4° e 6°C · 750ml · 11,5%',
    tag: 'Método Tradicional',
    tagStyle: 'background:var(--wine); color:var(--cream);',
    featured: false,
    safra: '2024',
    docura: 5, acidez: 78, corpo: 68, bolha: 90, final: 82,
    harmonizacaoChips: ['🦐 Frutos do mar', '🐟 Peixes', '🧀 Queijos curados', '🫒 Charcutaria', '🍤 Aperitivos finos'],
  },
  {
    id: 'espumante-rose-sur-lie-buzios',
    name: 'Sur Lie dos Búzios',
    nameFull: 'Espumante Rosé Sur Lie dos Búzios – Linha Inquietos',
    category: 'espumantes',
    subcategory: 'Linha Inquietos',
    price: 458,
    img: 'Imagens/Espumante Rosé Sur Lie dos Búzios – Linha Inquietos.png',
    bottleClass: 'bottle-rose',
    volume: '750ml',
    uvas: 'Blend',
    alcool: '12,2%',
    servico: '6°C',
    cor: 'Rosé vibrante em constante evolução',
    aroma: 'Brioche, frutas vermelhas e notas minerais',
    boca: 'Cremoso, complexo, sem licor de expedição',
    harmoniza: 'Queijos, canapés, pizzas e massas',
    descricao: '"Sur Lie" é um termo francês que significa "sobre as borras" — técnica em que o vinho amadurece em contato com as borras da fermentação e autólise, liberando compostos que agregam elegância, estrutura e cremosidade. Nosso Sur Lie não passa pelo dégorgement nem contém licor de expedição, mantendo-se em constante evolução até a garrafa ser aberta. Acompanhamento: queijos, canapés, pizzas e massas. Temperatura de serviço: 6°C · 750ml · 12,2%',
    tag: 'Linha Inquietos',
    tagStyle: 'background:var(--ink); color:var(--cream);',
    featured: true,
    safra: '2024',
    docura: 5, acidez: 85, corpo: 80, bolha: 95, final: 92,
    harmonizacaoChips: ['🧀 Queijos especiais', '🫒 Charcutaria fina', '🍕 Pizzas', '🥗 Canapés'],
  },

  /* ═══════════════════════════════════════════
     VINHOS ESPUMANTES — 750ml · R$ 58
  ═══════════════════════════════════════════ */
  {
    id: 'vinho-espumante-natural-rose-brut',
    name: 'Vinho Espumante Natural Rosé Brut',
    nameFull: 'Vinho Espumante Natural Rosé Brut',
    category: 'espumantes',
    subcategory: 'Vinho Espumante',
    price: 58,
    img: 'Imagens/Vinho Espumante Natural Rosé Brut.png',
    bottleClass: 'bottle-rose',
    volume: '750ml',
    uvas: 'Blend',
    alcool: '11%',
    servico: '4° a 6°C',
    cor: 'Rosé',
    aroma: 'Frutas vermelhas frescas',
    boca: 'Frutado, refrescante',
    harmoniza: 'Petiscos e aperitivos',
    descricao: 'Vinho espumante natural rosé brut, leve e refrescante. Ótima opção de entrada para quem está descobrindo os espumantes artesanais do sítio.',
    tag: 'Best-seller',
    tagStyle: '',
    featured: false,
    safra: '2024',
    docura: 22, acidez: 68, corpo: 45, bolha: 72, final: 60,
    harmonizacaoChips: ['🍤 Petiscos', '🧀 Queijos frescos', '🥗 Aperitivos', '🎉 Brindes'],
  },
  {
    id: 'vinho-espumante-natural-branco-brut',
    name: 'Vinho Espumante Natural Branco Brut',
    nameFull: 'Vinho Espumante Natural Branco Brut',
    category: 'espumantes',
    subcategory: 'Vinho Espumante',
    price: 58,
    img: 'Imagens/Vinho Espumante Natural Branco Brut.png',
    bottleClass: 'bottle-branco',
    volume: '750ml',
    uvas: 'Chardonnay',
    alcool: '11%',
    servico: '4° a 6°C',
    cor: 'Amarelo-palha',
    aroma: 'Cítrico e frutado',
    boca: 'Fresco, bolha fina persistente',
    harmoniza: 'Frutos do mar, queijos e canapés',
    descricao: 'Vinho espumante natural branco brut. Fresco, com boa acidez e bolha persistente. Perfeito para qualquer ocasião.',
    tag: null,
    tagStyle: '',
    featured: false,
    safra: '2024',
    docura: 18, acidez: 70, corpo: 45, bolha: 72, final: 60,
    harmonizacaoChips: ['🦐 Frutos do mar', '🧀 Queijos', '🥗 Canapés', '🍤 Aperitivos'],
  },
  {
    id: 'vinho-moscatel-espumante-rose',
    name: 'Vinho Moscatel Espumante Rosé',
    nameFull: 'Vinho Moscatel Espumante Rosé',
    category: 'espumantes',
    subcategory: 'Vinho Moscatel',
    price: 58,
    img: 'Imagens/Vinho Moscatel Espumante Rosé.png',
    bottleClass: 'bottle-rose',
    volume: '750ml',
    uvas: 'Moscato',
    alcool: '7,5%',
    servico: '2° a 6°C',
    cor: 'Rosado brilhante com reflexos rubi',
    aroma: 'Frutas vermelhas frescas, cereja, morango, notas cítricas',
    boca: 'Cremoso, macio, acidez bem equilibrada',
    harmoniza: 'Sobremesas e aperitivos leves',
    descricao: 'Elaborado com uvas Moscatéis, coloração rosada brilhante com reflexos rubi. Perlage fino e persistente. No aroma, frutas vermelhas frescas, cereja, morango, notas cítricas. No paladar, cremoso, macio, acidez bem equilibrada. Temperatura de serviço: 2 a 6°C · 750ml · 7,5%',
    tag: null,
    tagStyle: '',
    featured: false,
    safra: '2024',
    docura: 70, acidez: 40, corpo: 35, bolha: 70, final: 50,
    harmonizacaoChips: ['🍓 Frutas', '🍰 Sobremesas', '🌸 Aperitivos'],
  },
  {
    id: 'vinho-moscatel-espumante-branco',
    name: 'Vinho Moscatel Espumante Branco',
    nameFull: 'Vinho Moscatel Espumante Branco',
    category: 'espumantes',
    subcategory: 'Vinho Moscatel',
    price: 58,
    img: 'Imagens/Vinho Moscatel Espumante Branco.png',
    bottleClass: 'bottle-branco',
    volume: '750ml',
    uvas: 'Moscato Branco',
    alcool: '7,5%',
    servico: '2° a 5°C',
    cor: 'Amarelo-palha com reflexos esverdeados',
    aroma: 'Floral, flores brancas e toque de mel',
    boca: 'Estrutura leve com excelente equilíbrio',
    harmoniza: 'Sobremesas, bolos e frutas',
    descricao: 'Elaborado com uvas Moscato Branco, apresenta agradável frescor, baixa graduação alcoólica e perlage persistente. Com coloração amarelo-palha e reflexos esverdeados; aroma floral, flores brancas e um toque de mel. No paladar apresenta uma estrutura leve com excelente equilíbrio. Temperatura de serviço: 2 a 5°C · 750ml · 7,5%',
    tag: null,
    tagStyle: '',
    featured: false,
    safra: '2024',
    docura: 72, acidez: 38, corpo: 35, bolha: 68, final: 48,
    harmonizacaoChips: ['🍑 Pêssego', '🍯 Mel', '🍰 Sobremesas', '🌸 Aperitivos'],
  },

  /* ═══════════════════════════════════════════
     VINHO ESPUMANTE BRANCO MOSCATEL — 750ml · R$ 91
  ═══════════════════════════════════════════ */
  {
    id: 'vinho-espumante-branco-moscatel',
    name: 'Espumante Branco Moscatel',
    nameFull: 'Vinho Espumante Branco Moscatel',
    category: 'espumantes',
    subcategory: 'Vinho Espumante',
    price: 91,
    img: 'Imagens/Vinho Espumante Branco Moscatel.png',
    bottleClass: 'bottle-branco',
    volume: '750ml',
    uvas: 'Moscato',
    alcool: '7,5%',
    servico: '4°C',
    cor: 'Amarelo claro e brilhante',
    aroma: 'Pêssego, frutas tropicais e mel',
    boca: 'Sabor doce e leve, perlage intensa',
    harmoniza: 'Bolos de casamento, saladas de frutas e sorvete',
    descricao: 'Elaborado a partir de uva Moscato através do método Asti. Possui coloração amarelo claro e brilhante com perlage intensa. Com aromas de pêssego, frutas tropicais e mel. Em boca possui sabor doce e leve. Harmoniza com bolos de casamento, saladas de frutas e sorvete. Temperatura de serviço: 4°C · 750ml · 7,5%',
    tag: null,
    tagStyle: '',
    featured: false,
    safra: '2024',
    docura: 75, acidez: 42, corpo: 38, bolha: 72, final: 52,
    harmonizacaoChips: ['🎂 Bolos de casamento', '🍑 Saladas de frutas', '🍦 Sorvete', '🌸 Aperitivos'],
  },

  /* ═══════════════════════════════════════════
     VINHOS FINOS TINTOS — 750ml · R$ 120
  ═══════════════════════════════════════════ */
  {
    id: 'vinho-fino-tinto-cabernet-sauvignon',
    name: 'Cabernet Sauvignon Seco',
    nameFull: 'Vinho Fino Tinto Seco Cabernet Sauvignon',
    category: 'vinhos',
    subcategory: 'Vinho Fino Tinto',
    price: 120,
    img: 'Imagens/Vinho Fino Tinto Seco Cabernet Sauvignon.png',
    bottleClass: 'bottle-tinto',
    volume: '750ml',
    uvas: 'Cabernet Sauvignon',
    alcool: '12%',
    servico: '16°C',
    cor: 'Vermelho rubi',
    aroma: 'Frutas vermelhas maduras, café e especiarias',
    boca: 'Denso e encorpado, boa persistência',
    harmoniza: 'Carnes vermelhas, queijos, massas, pizzas, cogumelos, chocolate e nozes',
    descricao: 'Coloração vermelho rubi. Aromas de frutas vermelhas maduras, café e especiarias. Em boca, denso e encorpado, boa persistência. Harmoniza com carnes vermelhas, queijos, massas, pizzas, cogumelos, chocolate e nozes. Temperatura de serviço: 16°C · 750ml · 12%',
    tag: 'Reserva',
    tagStyle: 'background:var(--wine); color:var(--cream);',
    featured: true,
    safra: '2023',
    docura: 5, acidez: 60, corpo: 85, bolha: 0, final: 80,
    harmonizacaoChips: ['🥩 Churrasco', '🧀 Queijos curados', '🍝 Massas', '🍄 Cogumelos', '🍫 Chocolate amargo'],
  },
  {
    id: 'vinho-fino-tinto-tannat',
    name: 'Tannat Seco',
    nameFull: 'Vinho Fino Tinto Seco Tannat',
    category: 'vinhos',
    subcategory: 'Vinho Fino Tinto',
    price: 120,
    img: 'Imagens/Vinho Fino Tinto Seco Tannat.png',
    bottleClass: 'bottle-tinto',
    volume: '750ml',
    uvas: 'Tannat',
    alcool: '12%',
    servico: '16°C',
    cor: 'Coloração intensa e viva',
    aroma: 'Frutas negras com notas de carvalho',
    boca: 'Volumoso, taninos firmes',
    harmoniza: 'Carnes vermelhas, queijos, molhos, sobremesas e pratos condimentados',
    descricao: 'Coloração intensa e viva, aromas de frutas negras com notas de carvalho. Em boca é um vinho volumoso. Harmoniza com carnes vermelhas, queijos, molhos, sobremesas e pratos condimentados. Temperatura de serviço: 16°C · 750ml · 12%',
    tag: null,
    tagStyle: '',
    featured: false,
    safra: '2023',
    docura: 5, acidez: 65, corpo: 90, bolha: 0, final: 85,
    harmonizacaoChips: ['🥩 Carnes vermelhas', '🧀 Queijos curados', '🫒 Charcutaria'],
  },
  {
    id: 'vinho-fino-tinto-merlot',
    name: 'Merlot Seco',
    nameFull: 'Vinho Fino Tinto Seco Merlot',
    category: 'vinhos',
    subcategory: 'Vinho Fino Tinto',
    price: 120,
    img: 'Imagens/Vinho Fino Tinto Seco Merlot.png',
    bottleClass: 'bottle-tinto',
    volume: '750ml',
    uvas: 'Merlot',
    alcool: '12%',
    servico: '16°C',
    cor: 'Vermelho brilhante com tons violáceos',
    aroma: 'Frutas vermelhas',
    boca: 'Leve e equilibrado, boa persistência',
    harmoniza: 'Carnes vermelhas e churrasco',
    descricao: 'De coloração vermelho brilhante com tons violáceos e aroma de frutas vermelhas. Em boca, leve e equilibrado, boa persistência. Harmonização com carnes vermelhas e churrasco. Temperatura de serviço: 16°C · 750ml · 12%',
    tag: null,
    tagStyle: '',
    featured: false,
    safra: '2023',
    docura: 8, acidez: 58, corpo: 75, bolha: 0, final: 75,
    harmonizacaoChips: ['🍝 Massas', '🫕 Risotos', '🥩 Carnes leves', '🧀 Queijos'],
  },

  /* ═══════════════════════════════════════════
     VINHOS FINOS BRANCOS — 750ml · R$ 120–150
  ═══════════════════════════════════════════ */
  {
    id: 'vinho-fino-branco-chardonnay',
    name: 'Chardonnay Seco',
    nameFull: 'Vinho Fino Branco Seco Chardonnay',
    category: 'vinhos',
    subcategory: 'Vinho Fino Branco',
    price: 120,
    img: 'Imagens/Vinho Fino Branco Seco Chardonnay.png',
    bottleClass: 'bottle-branco',
    volume: '750ml',
    uvas: 'Chardonnay',
    alcool: '12%',
    servico: '8°C',
    cor: 'Amarelo-palha',
    aroma: 'Frutado',
    boca: 'Vinho leve',
    harmoniza: 'Peixe e queijo',
    descricao: 'Coloração amarelo palha com aroma frutado. Em boca é um vinho leve. Acompanhamento: peixe e queijo. Temperatura de serviço: 8°C · 750ml · 12%',
    tag: null,
    tagStyle: '',
    featured: true,
    safra: '2024',
    docura: 5, acidez: 65, corpo: 72, bolha: 0, final: 70,
    harmonizacaoChips: ['🍝 Massas', '🦐 Frutos do mar', '🐟 Peixes', '🧀 Queijos brancos'],
  },
  {
    id: 'vinho-fino-branco-moscato-alexandria',
    name: 'Moscato de Alexandria',
    nameFull: 'Vinho Fino Branco Seco Moscato de Alexandria',
    category: 'vinhos',
    subcategory: 'Vinho Fino Branco',
    price: 150,
    img: 'Imagens/Vinho Fino Branco Seco Moscato de Alexandria.png',
    bottleClass: 'bottle-branco',
    volume: '750ml',
    uvas: 'Moscato de Alexandria',
    alcool: '12%',
    servico: '8°C',
    cor: 'Palha com pontos dourados',
    aroma: 'Floral e frutado com notas de maracujá e maçã verde',
    boca: 'Vinho leve',
    harmoniza: 'Sobremesas e frutos do mar',
    descricao: 'Coloração palha com pontos dourados. Aromas florais e frutados com notas de maracujá e maçã verde. Em boca é um vinho leve. Acompanha sobremesas e frutos do mar. Temperatura de serviço: 8°C · 750ml · 12%',
    tag: null,
    tagStyle: '',
    featured: false,
    safra: '2024',
    docura: 10, acidez: 70, corpo: 68, bolha: 0, final: 72,
    harmonizacaoChips: ['🦐 Frutos do mar', '🐟 Peixes', '🧀 Queijos frescos', '🫒 Defumados'],
  },

  /* ═══════════════════════════════════════════
     VINHO DE MESA — 750ml
  ═══════════════════════════════════════════ */
  {
    id: 'vinho-mesa-branco-moscato',
    name: 'Branco Seco Moscato',
    nameFull: 'Vinho de Mesa Branco Seco Moscato',
    category: 'vinhos',
    subcategory: 'Vinho de Mesa',
    price: 75,
    img: 'Imagens/Vinho de Mesa branco Seco Moscato.png',
    bottleClass: 'bottle-branco',
    volume: '750ml',
    uvas: 'Moscato',
    alcool: '11%',
    servico: '6°C',
    cor: 'Amarelo-palha',
    aroma: 'Frutado',
    boca: 'Vinho leve',
    harmoniza: 'Peixes, carnes, aves, queijos, sobremesas e frutas',
    descricao: 'Coloração amarelo palha, aroma frutado. Em boca é um vinho leve. Harmoniza com peixes, carnes, aves, queijos, sobremesas e frutas. Temperatura de serviço: 6°C · 750ml · 11%',
    tag: null,
    tagStyle: '',
    featured: false,
    safra: '2024',
    docura: 8, acidez: 60, corpo: 45, bolha: 0, final: 55,
    harmonizacaoChips: ['🥗 Saladas', '🐟 Peixes', '🍝 Massas leves', '🍤 Petiscos'],
  },
  {
    id: 'vinho-mesa-tinto-suave',
    name: 'Tinto Suave Isabel',
    nameFull: 'Vinho de Mesa Tinto Suave',
    category: 'vinhos',
    subcategory: 'Vinho de Mesa',
    price: 25,
    img: 'Imagens/Vinho de Mesa Tinto Suave.png',
    bottleClass: 'bottle-tinto',
    volume: '750ml',
    uvas: 'Isabel',
    alcool: '10,5%',
    servico: '10° a 15°C',
    cor: 'Rubi com reflexos violáceos',
    aroma: 'Frutado e delicado, notas de frutas vermelhas e nuances florais',
    boca: 'Retrogosto suave, corpo médio, textura aveludada',
    harmoniza: 'Guisados, suflês, massas frescas e sobremesas leves',
    descricao: 'Elaborado de uvas Isabel, coloração rubi com reflexos violáceos. Aroma frutado e delicado, notas de frutas vermelhas e nuances florais. Vinho agradável, retrogosto suave, corpo médio, textura aveludada. Harmoniza com guisados, suflês, massas frescas e sobremesas leves. Temperatura de serviço: 10°C a 15°C · 750ml · 10,5%',
    tag: null,
    tagStyle: '',
    featured: false,
    safra: '2024',
    docura: 45, acidez: 52, corpo: 55, bolha: 0, final: 50,
    harmonizacaoChips: ['🫕 Guisados', '🍝 Massas frescas', '🧀 Queijos', '🍰 Sobremesas leves'],
  },

  /* ═══════════════════════════════════════════
     SUCOS INTEGRAIS
  ═══════════════════════════════════════════ */
  {
    id: 'suco-uva-tinto-integral',
    name: 'Suco de Uva Tinto Integral',
    nameFull: 'Suco de Uva Tinto – Integral',
    category: 'sucos',
    subcategory: 'Suco Integral',
    price: 35,
    img: 'Imagens/Suco de Uva Tinto – Integral.png',
    bottleClass: 'bottle-suco',
    volume: '1L',
    uvas: 'Bordô',
    alcool: '0%',
    servico: 'Gelado',
    cor: 'Vermelho intenso',
    aroma: 'Uva fresca, doce natural',
    boca: '100% integral, sem adição de açúcar',
    harmoniza: 'Puro, com gelo, cafés da manhã, crianças',
    descricao: 'Suco de uva tinto 100% integral, sem adição de açúcar ou conservantes. Prensagem natural para preservar o sabor e os nutrientes da uva Bordô cultivada no sítio.',
    tag: '100% uva',
    tagStyle: 'background:var(--gold); color:var(--ink);',
    featured: true,
    safra: '2024',
    harmonizacaoChips: ['🥂 Puro gelado', '🍳 Café da manhã', '🧃 Com gelo', '👧 Para crianças'],
  },
  {
    id: 'suco-bergamota',
    name: 'Suco de Bergamota',
    nameFull: 'Suco de Bergamota',
    category: 'sucos',
    subcategory: 'Suco Integral',
    price: 35,
    img: 'Imagens/Suco de Bergamota.png',
    bottleClass: 'bottle-laranja',
    volume: '1L',
    uvas: 'Bergamota',
    alcool: '0%',
    servico: 'Gelado',
    cor: 'Laranja vibrante',
    aroma: 'Cítrico, fresco e natural',
    boca: 'Natural, sem adição de açúcar',
    harmoniza: 'Puro, com gelo, cafés da manhã',
    descricao: 'Suco de bergamota 100% natural, rico em vitaminas e nutrientes. Produzido sem conservantes nem açúcares artificiais, processado para preservar os benefícios da fruta. Cor vibrante e sabor leve, perfeito para começar o dia.',
    tag: null,
    tagStyle: '',
    featured: false,
    safra: '2024',
    harmonizacaoChips: ['🥂 Puro gelado', '🍳 Café da manhã', '🧃 Com gelo'],
  },

  /* ═══════════════════════════════════════════
     KATATS — Vinho em lata
  ═══════════════════════════════════════════ */
  {
    id: 'katats-unidade',
    name: 'Katats — Unidade',
    nameFull: 'Katats — Vinho em Lata (unidade)',
    category: 'katats',
    subcategory: 'Vinho em Lata',
    price: 19,
    img: 'Imagens/Katats.png',
    bottleClass: 'bottle-branco',
    volume: '269ml (lata)',
    uvas: 'Vinho branco fino',
    alcool: '11%',
    servico: '4° a 8°C',
    cor: 'Amarelo-palha, límpido e brilhante',
    aroma: 'Pêssego maduro com notas sutis de mel',
    boca: 'Leve, refrescante e suave, borbulhas finas',
    harmoniza: 'Aperitivos, petiscos, praia, piscina, eventos',
    descricao: 'Elaborado a partir de vinho branco fino, apresenta coloração amarelo-palha, límpido e brilhante, com borbulhas finas e intensas. O aroma remete a pêssego maduro, com notas sutis de mel. Em boca, é leve, refrescante e suave.',
    tag: 'Novidade',
    tagStyle: '',
    featured: false,
    safra: '2024',
    harmonizacaoChips: ['🏖️ Praia', '🏊 Piscina', '🍤 Petiscos', '🎉 Eventos'],
  },
  {
    id: 'katats-fardo',
    name: 'Katats — Fardo (12 un.)',
    nameFull: 'Katats — Vinho em Lata, fardo com 12 unidades',
    category: 'katats',
    subcategory: 'Vinho em Lata',
    price: 228,
    img: 'Imagens/Katats.png',
    bottleClass: 'bottle-branco',
    volume: '12 × 269ml',
    uvas: 'Vinho branco fino',
    alcool: '11%',
    servico: '4° a 8°C',
    cor: 'Amarelo-palha',
    aroma: 'Pêssego maduro com notas sutis de mel',
    boca: 'Leve, refrescante e suave',
    harmoniza: 'Eventos, festas, churrascos, reuniões',
    descricao: 'Caixa com 12 latas Katats. Melhor custo por unidade — R$ 19 cada. Ideal para eventos, festas e quem quer ter sempre um Katats gelado à mão.',
    tag: 'Melhor valor',
    tagStyle: 'background:var(--green); color:var(--cream);',
    featured: false,
    safra: '2024',
    harmonizacaoChips: ['🎉 Eventos', '🍖 Churrascos', '👫 Reuniões', '🎊 Festas'],
  },

];

/* ═══════════════════════════════════════════
   Helpers
═══════════════════════════════════════════ */

function getProduto(id) {
  return PRODUTOS.find(p => p.id === id) || null;
}

function getProdutosPorCategoria(cat) {
  if (!cat || cat === 'todos') return PRODUTOS;
  return PRODUTOS.filter(p => p.category === cat);
}

function bottleSVG(cls) {
  return `<svg class="bottle-svg ${cls}" viewBox="0 0 120 360"><use href="#bottle"/></svg>`;
}

function formatPrice(price) {
  return 'R$ ' + price.toLocaleString('pt-BR', { minimumFractionDigits: 2 });
}
