/* produtos.js — Catálogo completo · Sítio Rosa do Vale */

const PRODUTOS = [

  /* ═══════════════════════════════════════════
     ESPUMANTES NATURAIS — 750ml · R$ 98
  ═══════════════════════════════════════════ */
  {
    id: 'espumante-natural-rose-brut',
    name: 'Espumante Natural Rosé Brut',
    nameFull: 'Espumante Natural Rosé Brut',
    category: 'espumantes',
    subcategory: 'Espumante Natural',
    price: 98,
    bottleClass: 'bottle-rose',
    volume: '750ml',
    uvas: 'Chardonnay, Riesling Itálico e Merlot',
    alcool: '11,5%',
    servico: '4° a 6°C',
    cor: 'Rosé salmão, brilhante',
    aroma: 'Framboesa, morango e amora',
    boca: 'Fresco e frutado, bolha fina persistente',
    harmoniza: 'Risotos, queijos e canapés',
    descricao: 'Elaborado a partir de uvas Chardonnay, Riesling Itálico e Merlot, em autoclaves, apresenta coloração salmão. Possui aromas de frutas vermelhas como framboesa, morango e amora. Em boca é fresco e frutado. Acompanhamento: risotos, queijos e canapés.',
    tag: 'Novidade',
    tagStyle: '',
    featured: true,
    safra: '2024',
    doçura: 20, acidez: 75, corpo: 55, bolha: 80, final: 70,
    harmonizacaoChips: ['🦐 Frutos do mar', '🧀 Queijos brancos', '🥗 Saladas com frutas', '🍓 Morango e framboesa', '🍤 Aperitivos'],
  },
  {
    id: 'espumante-natural-branco-brut',
    name: 'Espumante Natural Branco Brut',
    nameFull: 'Espumante Natural Branco Brut',
    category: 'espumantes',
    subcategory: 'Espumante Natural',
    price: 98,
    bottleClass: 'bottle-branco',
    volume: '750ml',
    uvas: 'Chardonnay e Riesling Itálico',
    alcool: '11,5%',
    servico: '4° a 6°C',
    cor: 'Amarelo-palha, brilhante',
    aroma: 'Frutado com notas cítricas',
    boca: 'Frescor e leveza, bolha fina',
    harmoniza: 'Queijos, canapés, pizzas e massas',
    descricao: 'Elaborado a partir de uvas Chardonnay e Riesling Itálico, em autoclaves, apresenta coloração amarelo-palha e aromas frutados com notas cítricas. Em boca apresenta frescor e leveza. Acompanhamento: queijos, canapés, pizzas e massas.',
    tag: null,
    tagStyle: '',
    featured: false,
    safra: '2024',
    doçura: 18, acidez: 72, corpo: 50, bolha: 80, final: 65,
    harmonizacaoChips: ['🧀 Queijos', '🍕 Pizzas', '🍝 Massas', '🥗 Canapés', '🍤 Aperitivos'],
  },
  {
    id: 'espumante-branco-demi-sec',
    name: 'Espumante Branco Demi Sec',
    nameFull: 'Espumante Branco Demi Sec',
    category: 'espumantes',
    subcategory: 'Espumante Natural',
    price: 98,
    bottleClass: 'bottle-branco',
    volume: '750ml',
    uvas: 'Chardonnay e Riesling Itálico',
    alcool: '11,5%',
    servico: '4° a 6°C',
    cor: 'Amarelo-palha',
    aroma: 'Frutado, levemente adocicado',
    boca: 'Demi-sec, equilibrado e agradável',
    harmoniza: 'Sobremesas, bolos e frutas',
    descricao: 'Espumante branco demi-sec elaborado a partir de Chardonnay e Riesling Itálico. Frutado, com acidez equilibrada e uma doçura suave que combina com sobremesas e como aperitivo festivo.',
    tag: null,
    tagStyle: '',
    featured: false,
    safra: '2024',
    doçura: 50, acidez: 60, corpo: 50, bolha: 75, final: 60,
    harmonizacaoChips: ['🍰 Sobremesas', '🍓 Frutas', '🎂 Bolos', '🍫 Chocolates brancos'],
  },
  {
    id: 'espumante-moscatel-rose',
    name: 'Espumante Moscatel Rosé',
    nameFull: 'Espumante Moscatel Rosé',
    category: 'espumantes',
    subcategory: 'Espumante Moscatel',
    price: 91,
    bottleClass: 'bottle-rose',
    volume: '750ml',
    uvas: 'Moscato',
    alcool: '9%',
    servico: '4° a 6°C',
    cor: 'Rosé, límpido',
    aroma: 'Floral intenso e frutas brancas',
    boca: 'Suave, moscatel, bolha fina',
    harmoniza: 'Sobremesas, frutas e aperitivos leves',
    descricao: 'Espumante moscatel rosé com perfil suave e aromático. Notas florais e de frutas brancas características do Moscato. Levemente adocicado, ideal para brindar em qualquer ocasião.',
    tag: null,
    tagStyle: '',
    featured: false,
    safra: '2024',
    doçura: 65, acidez: 45, corpo: 40, bolha: 75, final: 55,
    harmonizacaoChips: ['🍓 Frutas vermelhas', '🍰 Sobremesas', '🌸 Aperitivos leves', '🍫 Chocolates'],
  },

  /* ═══════════════════════════════════════════
     VINHOS ESPUMANTES — 750ml · R$ 58
  ═══════════════════════════════════════════ */
  {
    id: 'vinho-espumante-natural-rose-brut',
    name: 'Vinho Espumante Natural Rosé Brut',
    nameFull: 'Vinho Espumante Natural Rosé Brut',
    category: 'espumantes',
    subcategory: 'Vinho Espumante',
    price: 58,
    bottleClass: 'bottle-rose',
    volume: '750ml',
    uvas: 'Blend',
    alcool: '11%',
    servico: '4° a 6°C',
    cor: 'Rosé',
    aroma: 'Frutas vermelhas frescas',
    boca: 'Frutado, refrescante',
    harmoniza: 'Petiscos e aperitivos',
    descricao: 'Vinho espumante natural rosé brut, leve e refrescante. Ótima opção de entrada para quem está descobrindo os espumantes artesanais do sítio.',
    tag: 'Best-seller',
    tagStyle: '',
    featured: false,
    safra: '2024',
    doçura: 22, acidez: 68, corpo: 45, bolha: 72, final: 60,
    harmonizacaoChips: ['🍤 Petiscos', '🧀 Queijos frescos', '🥗 Aperitivos', '🎉 Brindes'],
  },
  {
    id: 'vinho-espumante-natural-branco-brut',
    name: 'Vinho Espumante Natural Branco Brut',
    nameFull: 'Vinho Espumante Natural Branco Brut',
    category: 'espumantes',
    subcategory: 'Vinho Espumante',
    price: 58,
    bottleClass: 'bottle-branco',
    volume: '750ml',
    uvas: 'Chardonnay',
    alcool: '11%',
    servico: '4° a 6°C',
    cor: 'Amarelo-palha',
    aroma: 'Cítrico e frutado',
    boca: 'Fresco, bolha fina persistente',
    harmoniza: 'Frutos do mar, queijos e canapés',
    descricao: 'Vinho espumante natural branco brut. Fresco, com boa acidez e bolha persistente. Perfeito para qualquer ocasião.',
    tag: null,
    tagStyle: '',
    featured: false,
    safra: '2024',
    doçura: 18, acidez: 70, corpo: 45, bolha: 72, final: 60,
    harmonizacaoChips: ['🦐 Frutos do mar', '🧀 Queijos', '🥗 Canapés', '🍤 Aperitivos'],
  },
  {
    id: 'vinho-moscatel-espumante-rose',
    name: 'Vinho Moscatel Espumante Rosé',
    nameFull: 'Vinho Moscatel Espumante Rosé',
    category: 'espumantes',
    subcategory: 'Vinho Moscatel',
    price: 58,
    bottleClass: 'bottle-rose',
    volume: '750ml',
    uvas: 'Moscato',
    alcool: '9%',
    servico: '4° a 6°C',
    cor: 'Rosé suave',
    aroma: 'Moscatel, floral',
    boca: 'Suave e aromático',
    harmoniza: 'Sobremesas e aperitivos leves',
    descricao: 'Moscatel espumante rosé, suave e aromático. Notas florais intensas e sabor de moscatel característico. Levemente adocicado.',
    tag: null,
    tagStyle: '',
    featured: false,
    safra: '2024',
    doçura: 70, acidez: 40, corpo: 35, bolha: 70, final: 50,
    harmonizacaoChips: ['🍓 Frutas', '🍰 Sobremesas', '🌸 Aperitivos'],
  },
  {
    id: 'vinho-moscatel-espumante-branco',
    name: 'Vinho Moscatel Espumante Branco',
    nameFull: 'Vinho Moscatel Espumante Branco',
    category: 'espumantes',
    subcategory: 'Vinho Moscatel',
    price: 58,
    bottleClass: 'bottle-branco',
    volume: '750ml',
    uvas: 'Moscato',
    alcool: '9%',
    servico: '4° a 6°C',
    cor: 'Amarelo dourado',
    aroma: 'Moscatel, mel e pêssego',
    boca: 'Suave, aromático e refrescante',
    harmoniza: 'Sobremesas, bolos e frutas',
    descricao: 'Vinho moscatel espumante branco com aroma intenso de moscatel e notas de mel e pêssego. Suave, refrescante e muito agradável.',
    tag: null,
    tagStyle: '',
    featured: false,
    safra: '2024',
    doçura: 72, acidez: 38, corpo: 35, bolha: 68, final: 48,
    harmonizacaoChips: ['🍑 Pêssego', '🍯 Mel', '🍰 Sobremesas', '🌸 Aperitivos'],
  },

  /* ═══════════════════════════════════════════
     VINHOS FINOS TINTOS — 750ml · R$ 120
  ═══════════════════════════════════════════ */
  {
    id: 'vinho-fino-tinto-cabernet-sauvignon',
    name: 'Cabernet Sauvignon Seco',
    nameFull: 'Vinho Fino Tinto Seco Cabernet Sauvignon',
    category: 'vinhos',
    subcategory: 'Vinho Fino Tinto',
    price: 120,
    bottleClass: 'bottle-tinto',
    volume: '750ml',
    uvas: 'Cabernet Sauvignon',
    alcool: '12%',
    servico: '16°C',
    cor: 'Vermelho rubi',
    aroma: 'Frutas vermelhas maduras, café e especiarias',
    boca: 'Denso e encorpado, boa persistência',
    harmoniza: 'Carnes vermelhas, queijos, massas, pizzas, cogumelos, chocolate e nozes',
    descricao: 'Coloração vermelho rubi. Com aromas de frutas vermelhas maduras, café e especiarias. Em boca, é denso e encorpado, apresentando boa persistência. Harmoniza com carnes vermelhas, queijos, massas, pizzas, cogumelos, chocolate e nozes.',
    tag: 'Reserva',
    tagStyle: 'background:var(--wine); color:var(--cream);',
    featured: true,
    safra: '2023',
    doçura: 5, acidez: 60, corpo: 85, bolha: 0, final: 80,
    harmonizacaoChips: ['🥩 Churrasco', '🧀 Queijos curados', '🍝 Massas', '🍄 Cogumelos', '🍫 Chocolate amargo'],
  },
  {
    id: 'vinho-fino-tinto-tannat',
    name: 'Tannat Seco',
    nameFull: 'Vinho Fino Tinto Seco Tannat',
    category: 'vinhos',
    subcategory: 'Vinho Fino Tinto',
    price: 120,
    bottleClass: 'bottle-tinto',
    volume: '750ml',
    uvas: 'Tannat',
    alcool: '12,5%',
    servico: '16°C',
    cor: 'Vermelho rubi intenso',
    aroma: 'Ameixa, especiarias e taninos firmes',
    boca: 'Encorpado, estruturado, taninos firmes',
    harmoniza: 'Churrasco, carnes vermelhas, queijos curados',
    descricao: 'Vinho fino tinto seco Tannat. Coloração vermelho rubi intenso, com aromas de ameixa e especiarias. Encorpado e estruturado, com taninos firmes que evoluem bem.',
    tag: null,
    tagStyle: '',
    featured: false,
    safra: '2023',
    doçura: 5, acidez: 65, corpo: 90, bolha: 0, final: 85,
    harmonizacaoChips: ['🥩 Carnes vermelhas', '🧀 Queijos curados', '🫒 Charcutaria'],
  },
  {
    id: 'vinho-fino-tinto-merlot',
    name: 'Merlot Seco',
    nameFull: 'Vinho Fino Tinto Seco Merlot',
    category: 'vinhos',
    subcategory: 'Vinho Fino Tinto',
    price: 120,
    bottleClass: 'bottle-tinto',
    volume: '750ml',
    uvas: 'Merlot',
    alcool: '12%',
    servico: '16°C',
    cor: 'Vermelho rubi aveludado',
    aroma: 'Frutas vermelhas, ameixa e chocolate suave',
    boca: 'Macio, aveludado, taninos macios',
    harmoniza: 'Massas, risotos, carnes leves, queijos',
    descricao: 'Vinho fino tinto seco Merlot. Coloração vermelho rubi aveludado, com aromas de frutas vermelhas, ameixa e notas de chocolate suave. Macio e aveludado em boca.',
    tag: null,
    tagStyle: '',
    featured: false,
    safra: '2023',
    doçura: 8, acidez: 58, corpo: 75, bolha: 0, final: 75,
    harmonizacaoChips: ['🍝 Massas', '🫕 Risotos', '🥩 Carnes leves', '🧀 Queijos'],
  },

  /* ═══════════════════════════════════════════
     VINHOS FINOS BRANCOS — 750ml · R$ 120–150
  ═══════════════════════════════════════════ */
  {
    id: 'vinho-fino-branco-chardonnay',
    name: 'Chardonnay Seco',
    nameFull: 'Vinho Fino Branco Seco Chardonnay',
    category: 'vinhos',
    subcategory: 'Vinho Fino Branco',
    price: 120,
    bottleClass: 'bottle-branco',
    volume: '750ml',
    uvas: 'Chardonnay',
    alcool: '12%',
    servico: '10° a 12°C',
    cor: 'Amarelo-palha com reflexos dourados',
    aroma: 'Tropical, baunilha e manteiga',
    boca: 'Encorpado, mineral, longo',
    harmoniza: 'Massas, risotos, peixes e frutos do mar, queijos brie e camembert',
    descricao: 'Vinho fino branco seco Chardonnay. Amarelo-palha com reflexos dourados. Aromas tropicais com notas de baunilha. Encorpado e mineral, com final persistente.',
    tag: null,
    tagStyle: '',
    featured: true,
    safra: '2024',
    doçura: 5, acidez: 65, corpo: 72, bolha: 0, final: 70,
    harmonizacaoChips: ['🍝 Massas', '🦐 Frutos do mar', '🐟 Peixes', '🧀 Queijos brancos'],
  },
  {
    id: 'vinho-fino-branco-moscato-alexandria',
    name: 'Moscato de Alexandria',
    nameFull: 'Vinho Fino Branco Seco Moscato de Alexandria',
    category: 'vinhos',
    subcategory: 'Vinho Fino Branco',
    price: 150,
    bottleClass: 'bottle-branco',
    volume: '750ml',
    uvas: 'Moscato de Alexandria',
    alcool: '12%',
    servico: '10° a 12°C',
    cor: 'Dourado brilhante',
    aroma: 'Floral intenso, mel e damasco',
    boca: 'Aromático, mineral, persistente',
    harmoniza: 'Frutos do mar, peixes, queijos frescos e defumados',
    descricao: 'Vinho fino branco seco Moscato de Alexandria. Dourado brilhante, com aroma floral intenso e notas de mel e damasco. Mineral e aromático, com final elegante.',
    tag: null,
    tagStyle: '',
    featured: false,
    safra: '2024',
    doçura: 10, acidez: 70, corpo: 68, bolha: 0, final: 72,
    harmonizacaoChips: ['🦐 Frutos do mar', '🐟 Peixes', '🧀 Queijos frescos', '🫒 Defumados'],
  },

  /* ═══════════════════════════════════════════
     VINHO DE MESA — 750ml · R$ 75
  ═══════════════════════════════════════════ */
  {
    id: 'vinho-mesa-branco-moscato',
    name: 'Branco Seco Moscato',
    nameFull: 'Vinho de Mesa Branco Seco Moscato',
    category: 'vinhos',
    subcategory: 'Vinho de Mesa',
    price: 75,
    bottleClass: 'bottle-branco',
    volume: '750ml',
    uvas: 'Moscato',
    alcool: '11%',
    servico: '10° a 12°C',
    cor: 'Amarelo-claro',
    aroma: 'Moscatel suave e floral',
    boca: 'Leve, refrescante e seco',
    harmoniza: 'Saladas, peixes, massas leves, petiscos',
    descricao: 'Vinho de mesa branco seco com uvas Moscato. Leve, refrescante, com notas florais suaves. Ótima opção para o dia a dia e para quem está começando a explorar os vinhos artesanais.',
    tag: null,
    tagStyle: '',
    featured: false,
    safra: '2024',
    doçura: 8, acidez: 60, corpo: 45, bolha: 0, final: 55,
    harmonizacaoChips: ['🥗 Saladas', '🐟 Peixes', '🍝 Massas leves', '🍤 Petiscos'],
  },

  /* ═══════════════════════════════════════════
     SUCOS INTEGRAIS
  ═══════════════════════════════════════════ */
  {
    id: 'suco-uva-tinto-integral',
    name: 'Suco de Uva Tinto Integral',
    nameFull: 'Suco de Uva Tinto – Integral',
    category: 'sucos',
    subcategory: 'Suco Integral',
    price: 35,
    bottleClass: 'bottle-suco',
    volume: '1L',
    uvas: 'Bordô',
    alcool: '0%',
    servico: 'Gelado',
    cor: 'Vermelho intenso',
    aroma: 'Uva fresca, doce natural',
    boca: '100% integral, sem adição de açúcar',
    harmoniza: 'Puro, com gelo, cafés da manhã, crianças',
    descricao: 'Suco de uva tinto 100% integral, sem adição de açúcar ou conservantes. Prensagem natural para preservar o sabor e os nutrientes da uva Bordô cultivada no sítio.',
    tag: '100% uva',
    tagStyle: 'background:var(--gold); color:var(--ink);',
    featured: true,
    safra: '2024',
    harmonizacaoChips: ['🥂 Puro gelado', '🍳 Café da manhã', '🧃 Com gelo', '👧 Para crianças'],
  },
  {
    id: 'suco-bergamota',
    name: 'Suco de Bergamota',
    nameFull: 'Suco de Bergamota',
    category: 'sucos',
    subcategory: 'Suco Integral',
    price: 35,
    bottleClass: 'bottle-laranja',
    volume: '1L',
    uvas: 'Bergamota',
    alcool: '0%',
    servico: 'Gelado',
    cor: 'Laranja vibrante',
    aroma: 'Cítrico, fresco e natural',
    boca: 'Natural, sem adição de açúcar',
    harmoniza: 'Puro, com gelo, cafés da manhã',
    descricao: 'Suco de bergamota 100% integral, sem adição de açúcar ou conservantes. Colhida no sítio, prensada e engarrafada no ponto certo de maturação.',
    tag: null,
    tagStyle: '',
    featured: false,
    safra: '2024',
    harmonizacaoChips: ['🥂 Puro gelado', '🍳 Café da manhã', '🧃 Com gelo'],
  },

  /* ═══════════════════════════════════════════
     KATATS — Vinho em lata
  ═══════════════════════════════════════════ */
  {
    id: 'katats-unidade',
    name: 'Katats — Unidade',
    nameFull: 'Katats — Vinho em Lata (unidade)',
    category: 'katats',
    subcategory: 'Vinho em Lata',
    price: 19,
    bottleClass: 'bottle-branco',
    volume: '269ml (lata)',
    uvas: 'Vinho branco fino',
    alcool: '11%',
    servico: '4° a 8°C',
    cor: 'Amarelo-palha, límpido e brilhante',
    aroma: 'Pêssego maduro com notas sutis de mel',
    boca: 'Leve, refrescante e suave, borbulhas finas',
    harmoniza: 'Aperitivos, petiscos, praia, piscina, eventos',
    descricao: 'Elaborado a partir de vinho branco fino, apresenta coloração amarelo-palha, límpido e brilhante, com borbulhas finas e intensas. O aroma remete a pêssego maduro, com notas sutis de mel. Em boca, é leve, refrescante e suave.',
    tag: 'Novidade',
    tagStyle: '',
    featured: false,
    safra: '2024',
    harmonizacaoChips: ['🏖️ Praia', '🏊 Piscina', '🍤 Petiscos', '🎉 Eventos'],
  },
  {
    id: 'katats-fardo',
    name: 'Katats — Fardo (12 un.)',
    nameFull: 'Katats — Vinho em Lata, fardo com 12 unidades',
    category: 'katats',
    subcategory: 'Vinho em Lata',
    price: 228,
    bottleClass: 'bottle-branco',
    volume: '12 × 269ml',
    uvas: 'Vinho branco fino',
    alcool: '11%',
    servico: '4° a 8°C',
    cor: 'Amarelo-palha',
    aroma: 'Pêssego maduro com notas sutis de mel',
    boca: 'Leve, refrescante e suave',
    harmoniza: 'Eventos, festas, churrascos, reuniões',
    descricao: 'Caixa com 12 latas Katats. Melhor custo por unidade — R$ 19 cada. Ideal para eventos, festas e quem quer ter sempre um Katats gelado à mão.',
    tag: 'Melhor valor',
    tagStyle: 'background:var(--green); color:var(--cream);',
    featured: false,
    safra: '2024',
    harmonizacaoChips: ['🎉 Eventos', '🍖 Churrascos', '👫 Reuniões', '🎊 Festas'],
  },

];

/* ═══════════════════════════════════════════
   Helpers
═══════════════════════════════════════════ */

function getProduto(id) {
  return PRODUTOS.find(p => p.id === id) || null;
}

function getProdutosPorCategoria(cat) {
  if (!cat || cat === 'todos') return PRODUTOS;
  return PRODUTOS.filter(p => p.category === cat);
}

function bottleSVG(cls) {
  return `<svg class="bottle-svg ${cls}" viewBox="0 0 120 360"><use href="#bottle"/></svg>`;
}

function formatPrice(price) {
  return 'R$ ' + price.toLocaleString('pt-BR', { minimumFractionDigits: 2 });
}
